In [30]:
from sklearn.datasets import load_iris
iris = load_iris()
X, y = iris.data, iris.target
print(X.shape, y.shape)

((150, 4), (150,))


In [41]:
import numpy as np
rng = np.random.RandomState(0)

permutation = rng.permutation(len(X))
X, y = X[permutation], y[permutation]


In [42]:
from sklearn.cross_validation import train_test_split
np.random.seed(12162015)
train_X, test_X, train_y, test_y = train_test_split(X, y, train_size=0.5, random_state=1999)
print(train_X[:3])
train_X, test_X, train_y, test_y = train_test_split(X, y, train_size=0.5, random_state=1999)
print(train_X[:3])
print("Labels for training and testing data")


[[ 6.3  3.3  4.7  1.6]
 [ 5.4  3.9  1.7  0.4]
 [ 5.   3.3  1.4  0.2]]
[[ 6.3  3.3  4.7  1.6]
 [ 5.4  3.9  1.7  0.4]
 [ 5.   3.3  1.4  0.2]]
Labels for training and testing data
